spring.application.name=HMS
spring.datasource.url=jdbc:mysql://localhost:3306/hospital_management
spring.datasource.username=root
spring.datasource.password=ANIS02042008
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true